name: publish_merge_main.yml
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "github",
              "username": "Smart-POS-back-end",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
